### ISSUE TITLE
Request for Trained Weights

### ISSUE THREAD

**Issue by janru** [arthurflor23/handwritten-text-recognition#15]
Hi @arthurflor23 ,
thank you for the great medium article and clean tf2 implementation.
I started to train the model but due to my slow hardware it takes days to converge.
Actually right now I'm at a loss of 10.0 with bentham.
In your slides it looks like you trained the loss down to 0. something with all datasets.
Can you share your weights somehow?
Adding blobs to git is maybe not the best way to go, but maybe you can upload them somewhere else. You can also reply here and add files to the reply.
Would be very helpful.
Best, Jan

**Comment by arthurflor23** [comment]
Hello, Jan, thanks for your interest,
Unfortunately, today I am on a new project and I no longer have the weights. I explain in this [issue](https://github.com/arthurflor23/handwritten-text-recognition/issues/8) (in fact, I'm already on a third project since this issue). However, to be able to train is relatively fast via Colab, you know.. 1-2 hours of trained with the Tesla P100 or T4.
Looking at the presentation doc, I think it is currently possible to achieve better results as well.
